#!/bin/bash

cat <<EOF  >PGMFILE
+++++ +++++ [- >
 +++++ ++ >
 +++++ +++++ >
 +++++ +++++ + >
 ++++ >
 +++ >
 +++++ ++++ >
 +++++ +++++ + >
 +++++ +++++ >
 +++ <<<<< <<<<
]                        Print:
> ++ .                   "H"
> + .                    "e"
> -- .. +++ .            "llo"
> ++++ .                 comma
> ++ .                   space
> --- .                  "W"
> + . +++ . ----- - .    "orl"
> .                      "d"
> +++ .                  "!"
EOF

python3 $1 PGMFILE /dev/null

rm -f PGMFILE
